"""empty message

Revision ID: 696055ba507f
Revises: 98d779d0d21a
Create Date: 2017-09-22 16:23:15.874922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696055ba507f'
down_revision = '98d779d0d21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['main_comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcomment')
    # ### end Alembic commands ###
