"""add info about speaker to Comment

Revision ID: 99d45ddd138c
Revises: fdcd10f68ecd
Create Date: 2017-09-06 21:36:28.272810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d45ddd138c'
down_revision = 'fdcd10f68ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('speaker', sa.String(length=30), nullable=True))
    op.add_column('comment', sa.Column('speaker_avatar', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_comment_speaker'), 'comment', ['speaker'], unique=False)
    op.drop_index('ix_user_avatar', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_avatar', 'user', ['avatar'], unique=False)
    op.drop_index(op.f('ix_comment_speaker'), table_name='comment')
    op.drop_column('comment', 'speaker_avatar')
    op.drop_column('comment', 'speaker')
    op.drop_column('comment', 'posted')
    # ### end Alembic commands ###
