"""add relation between Article and User'

Revision ID: fdcd10f68ecd
Revises: 
Create Date: 2017-09-04 17:52:34.503987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdcd10f68ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_sign'), 'user', ['sign'], unique=False)
    op.drop_column('user', 'signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signature', mysql.VARCHAR(length=256), nullable=True))
    op.drop_index(op.f('ix_user_sign'), table_name='user')
    op.drop_column('user', 'sign')
    # ### end Alembic commands ###
